#!/bin/bash

mysql -uroot -p${MYSQL_ROOT_PASSWORD} -e "
CREATE DATABASE ${DATABASE_NAME};
CREATE USER '${DATABASE_USER}'@'%' IDENTIFIED BY '${DATABASE_PASSWORD}';
GRANT ALL ON ${DATABASE_NAME}.* TO '${DATABASE_USER}'@'%';"